### ISSUE TITLE
关于注册网站……

### ISSUE THREAD

**Issue by kellyiscute** [JRY-Zheng/Dancer#1]
建议加上HTTPS，letsEncrypt有免费的SSL证书
可以顺手去注册一个域名
freenom.com里面.tk域名是免费的
我可以帮忙的嘻嘻嘻

**Comment by kellyiscute** [comment]
学习了，谢谢

**Comment by JRY-Zheng** [comment]
> 建议加上HTTPS，letsEncrypt有免费的SSL证书
> 可以顺手去注册一个域名
> freenom.com里面.tk域名是免费的
> 我可以帮忙的嘻嘻嘻

啊网站我有了的。是https啊，[戳这里](https://sued-wind.cc/dancer)。虽然最近没什么时间折腾，但是非常感谢你的 issue！貌似是我的第一个 issue（捂脸
